### ISSUE TITLE
Issue : generate PSRA/DSRA profile indicators

### ISSUE THREAD

**Issue by wkhchow** [OpenDRR/opendrr-data-store#1]
issue - Current outputs on the scenario outputs are not clear to me and generating the specific 38 indicators looks like it needs to be manipulated in some ways.  Need to meetup with Murray, Tiegan and others for clarification.

end goal - create views based views based on indicators from the scenario outputs

**Comment by jvanulde** [comment]
@drotheram @wkhchow is this done?

**Comment by drotheram** [comment]
I do not believe this is complete for PSRA yet

**Comment by wkhchow** [comment]
DSRA ~ 95% complete.  Missing a few indicators, Murray still compiling lookup tables for them and should be completed soon.

PSRA ~ haven't started.  Murray is working on the transformation tables.
