### ISSUE TITLE
PostGIS Sandbox Environment

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/opendrr-data-store#12]
Create a sandbox environment with pre-processed scenario outputs. This sandbox will be used to generate static GeoJSON files from database views that can be ingested by RiskProfiler and GeoViewer visualizations.

**Comment by wkhchow** [comment]
Created separate set of identical views in different data types (numeric, float, text) to accommodate limitations in geojson/api.

Newest iteration of the views are rounded at 6 decimal places (numeric, float, text).
