### ISSUE TITLE
Update area_km2 / area_ha calculations with correct projection.  Update table/sql scripts accordingly.

### ISSUE THREAD

**Issue by wkhchow** [OpenDRR/opendrr-data-store#32]

**Comment by jvanulde** [comment]
@wkhchow can we update this issue please? Should we move to current Sprint (Sprint 24)?

**Comment by jvanulde** [comment]
@wkhchow was this addressed in https://github.com/OpenDRR/boundaries/commit/7ff1bbce37a7a0814acfb8ab4869dad95a1d1632 ?

**Comment by wkhchow** [comment]
addressed and pushed Dec 14, 2020.
