### ISSUE TITLE
Explore github actions to automate geopackage exports

### ISSUE THREAD

**Issue by wkhchow** [OpenDRR/opendrr-data-store#42]
Currently, geopackage exports of the db are generated locally on my win 10 desktop machine.  After newest stack build, Drew backups the db onto S3.  I restore the DB locally on my end to run my .bat gdal ogr2ogr scripts to generate the geopackage exports.  The geopackages are then uploaded to my cloud storage (one drive / google drive) for dissemination.  Whole process may take a few hours and upwards of 30+ gbs.
Would be great if able to automate this process and store the data somewhere (could be compressed?).

location of my bat scripts I use to run on local win 10 env.
https://github.com/OpenDRR/opendrr-data-store/tree/master/scripts/Data%20Export

**Comment by anthonyfok** [comment]
Thank you Will!

Here are my (early) random notes:

## GitHub Actions resource limits

From https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration:

> * Job execution time - Each job in a workflow can run for up to 6 hours of execution time. If a job reaches this limit, the job is terminated and fails to complete.
> * Workflow run time - Each workflow run is limited to 72 hours. If a workflow run reaches this limit, the workflow run is cancelled.

GitHub's offering is a lot more generous than I originally thought!

Disk space could be a limiting factor at around 14GB free space, though the GitHub Ubuntu runner has actually over 80GB of disk space but have so many pre-installed software that we don't need, so perhaps we could just conveniently erase them to get more working free space?  (haha, experimentation for another day)

## Some early plans on how to go about it

At first glance, there are many *.bat files involved, which we _could_ run using GitHub's Windows runner, or it might be easier to convert the .bat to .sh (with an Batch-to-Bash conversion script? to (a) save time and to (b) accommodate future changes to the .bat files?) to run on GitHub's Ubuntu runner.   Probably easier to getting everything to run properly on my local Debian machine first, etc.  Fun!

(There will be quite some experimentation involved, and definitely not as trivial as I first imagined.  So, yes, Joost's suggestion waiting till the next Sprint iteration is prudent and realistic.  Let's see how fast I can finish other existing tasks, hoho!)

**Comment by wkhchow** [comment]
Thanks for the early notes.  Definitely useful.  The bat files are not in order and not all have to be run.  Best we can have a discussion about it when the time comes so we can go over it and I can do some clean up as well.
