### ISSUE TITLE
aggregation hexbin geometry examples

### ISSUE THREAD

**Issue by wkhchow** [OpenDRR/opendrr-data-store#49]
write up some preaggregated hexbin geometry examples for comparison (ie ghsl layers).

**Comment by jvanulde** [comment]
@wkhchow I am adding this into the sprint backlog as per our planning session on July 5th

**Comment by wkhchow** [comment]
current ghsl hexbin aggregation examples (area) integrated into newest build.  Now looking into implementing the global-fabric grid as well.
