### ISSUE TITLE
investigate shakemap to filter out asset points

### ISSUE THREAD

**Issue by wkhchow** [OpenDRR/opendrr-data-store#51]
Current shakemap points/grid has asset/sauid points incorporated / interpolated for the settled area centroids.  For viewing purposes in ES, check to see if we can filter out those sauid points to only have grid points for shakemap

**Comment by jvanulde** [comment]
@wkhchow are we moving this to the current sprint?

**Comment by wkhchow** [comment]
Checking back on conversation with @drotheram and @tieganh back on July 23rd Tiegan said it will be better if the shakemap is left as is without filtering.  Closing this issue.
